# Datalab 2025-2026

**Groepsnummer:** 1 (klas 1D)

| Naam | Studentnummer |
|---|---|
| Skip van Leeuwen | 26137399 |
| Djojo van der Eerden | 26141159 |
| Gavin Giel | 26054388 |
| Jasper Wijngaarden | 26012693 |

In [27]:
# Import libraries

import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 200) # Hier kan je het aantal regels dat wordt weergegeven in je dataframe aanpassen
pd.set_option('display.max_columns', 200) # Hier kan je het aantal kolommen dat wordt weergegeven in je dataframe aanpassen

## Sprint 3

In [28]:
# run dit in terminal: pip install cbsodata
# Dataset importeren
import cbsodata 
cbsdata = pd.DataFrame(cbsodata.get_data('85618NED'))
cbsdata.shape

(18116, 128)

In [29]:
# Dataframe buurten maken
buurten = cbsdata[cbsdata['SoortRegio_2'].str.strip() == 'Buurt']
buurten.head()

,ID,WijkenEnBuurten,Gemeentenaam_1,SoortRegio_2,Codering_3,IndelingswijzigingGemeenteWijkBuurt_4,AantalInwoners_5,Mannen_6,Vrouwen_7,k_0Tot15Jaar_8,k_15Tot25Jaar_9,k_25Tot45Jaar_10,k_45Tot65Jaar_11,k_65JaarOfOuder_12,Ongehuwd_13,Gehuwd_14,Gescheiden_15,Verweduwd_16,Nederland_17,EuropaExclusiefNederland_18,BuitenEuropa_19,Nederland_20,EuropaExclusiefNederland_21,BuitenEuropa_22,EuropaExclusiefNederland_23,BuitenEuropa_24,GeboorteTotaal_25,GeboorteRelatief_26,SterfteTotaal_27,SterfteRelatief_28,HuishoudensTotaal_29,Eenpersoonshuishoudens_30,HuishoudensZonderKinderen_31,HuishoudensMetKinderen_32,GemiddeldeHuishoudensgrootte_33,Bevolkingsdichtheid_34,Woningvoorraad_35,GemiddeldeWOZWaardeVanWoningen_36,PercentageEengezinswoning_37,PercentageMeergezinswoning_38,PercentageBewoond_39,PercentageOnbewoond_40,Koopwoningen_41,HuurwoningenTotaal_42,InBezitWoningcorporatie_43,InBezitOverigeVerhuurders_44,EigendomOnbekend_45,BouwjaarVoor2000_46,BouwjaarVanaf2000_47,GemiddeldeElektriciteitsleveringTotaal_48,Appartement_49,Tussenwoning_50,Hoekwoning_51,TweeOnderEenKapWoning_52,VrijstaandeWoning_53,Huurwoning_54,EigenWoning_55,GemiddeldAardgasverbruikTotaal_56,Appartement_57,Tussenwoning_58,Hoekwoning_59,TweeOnderEenKapWoning_60,VrijstaandeWoning_61,Huurwoning_62,EigenWoning_63,PercentageWoningenMetStadsverwarming_64,LeerlingenPo_65,LeerlingenVoInclVavo_66,StudentenMboExclExtranei_67,StudentenHbo_68,StudentenWo_69,BasisonderwijsVmboMbo1_70,HavoVwoMbo24_71,HboWo_72,WerkzameBeroepsbevolking_73,Nettoarbeidsparticipatie_74,PercentageWerknemers_75,WerknemersMetVasteArbeidsrelatie_76,WerknemersMetFlexibeleArbeidsrelatie_77,PercentageZelfstandigen_78,AantalInkomensontvangers_79,GemiddeldInkomenPerInkomensontvanger_80,GemiddeldInkomenPerInwoner_81,k_40PersonenMetLaagsteInkomen_82,k_20PersonenMetHoogsteInkomen_83,GemGestandaardiseerdInkomenVanHuish_84,k_40HuishoudensMetLaagsteInkomen_85,k_20HuishoudensMetHoogsteInkomen_86,HuishoudensMetEenLaagInkomen_87,HuishOnderOfRondSociaalMinimum_88,HuishoudensTot110VanSociaalMinimum_89,HuishoudensTot120VanSociaalMinimum_90,MediaanVermogenVanParticuliereHuish_91,PersonenPerSoortUitkeringBijstand_92,PersonenPerSoortUitkeringAO_93,PersonenPerSoortUitkeringWW_94,PersonenPerSoortUitkeringAOW_95,JongerenMetJeugdzorgInNatura_96,PercentageJongerenMetJeugdzorg_97,WmoClienten_98,WmoClientenRelatief_99,BedrijfsvestigingenTotaal_100,ALandbouwBosbouwEnVisserij_101,BFNijverheidEnEnergie_102,GIHandelEnHoreca_103,HJVervoerInformatieEnCommunicatie_104,KLFinancieleDienstenOnroerendGoed_105,MNZakelijkeDienstverlening_106,OQOverheidOnderwijsEnZorg_107,RUCultuurRecreatieOverigeDiensten_108,PersonenautoSTotaal_109,PersonenautoSBrandstofBenzine_110,PersonenautoSOverigeBrandstof_111,PersonenautoSPerHuishouden_112,PersonenautoSNaarOppervlakte_113,Motorfietsen_114,AfstandTotHuisartsenpraktijk_115,AfstandTotGroteSupermarkt_116,AfstandTotKinderdagverblijf_117,AfstandTotSchool_118,ScholenBinnen3Km_119,OppervlakteTotaal_120,OppervlakteLand_121,OppervlakteWater_122,MeestVoorkomendePostcode_123,Dekkingspercentage_124,MateVanStedelijkheid_125,Omgevingsadressendichtheid_126
3,3,Annen,Aa en Hunze,Buurt,BU16800000,1,3450,1680,1775,495,355,615,1055,935,1395,1585,255,220,3220,100,135,3220,65,55,35,75,25,8.0,30,8.0,1520,440,575,515,2.3,1369.0,1584,333.0,90.0,10.0,96.0,4.0,74.0,26.0,20.0,6.0,0.0,88.0,12.0,2630.0,1380.0,1870.0,2350.0,2700.0,3350.0,1620.0,2980.0,1100.0,690.0,890.0,1000.0,1080.0,1340.0,870.0,1180.0,NaN,260,210,100,90,20,510.0,1160.0,870.0,1810,72.0,83.0,60.0,24.0,17.0,2900,39.6,33.4,38.5,21.1,43.6,30.1,23.4,1.4,3.0,5.1,7.5,235.6,40.0,110.0,20.0,880.0,85.0,10.8,250.0,73.0,375,15.0,50.0,65.0,10.0,35.0,85.0,75.0,40.0,2030,1555,480,1.3,806.0,210,0.8,0.8,0.5,0.8,2.5,252,252,0,9468,1.0,5.0,410.0
4,4,Verspreide huizen Annen,Aa en Hunze,Buurt,BU16800009,1,150,75,80,15,15,15,65,45,50,85,5,5,140,5,5,140,5,5,0,0,0,0.0,0,20.0,65,15,35,20,2.3,12.0,63,579.0,100.0,0.0,97.0,3.0,97.0,3.0,0.0,3.0,0.0,70.0,30.0,4240.0,NaN,NaN,NaN,NaN,4240.0,NaN,4270.0,1610.0,NaN,NaN,NaN,NaN,1610.0,NaN,1620.0,NaN,10,10,0,0,0,NaN,NaN,NaN,80,NaN,NaN,NaN,NaN,NaN,100,55.4,49.5,30.6,36.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,40.0,NaN,NaN,NaN,NaN,30,10.0,0.0,0.0,0.0,0.0,10.0,5.0,5.0,100,75,25,1.5,8.0,10,2.6,2.1,1.8,2.0,1.2,1226,1213,13,9468,1.0,5.0,59.0
6,6,Eext,Aa en Hunze,Buurt,BU16800100,1,1270,655,620,185,140,280,390,275,565,550,95,65,1195,40,40,1190,20,15,20,20,20,15.0,0,2.0,550,155,205,190,2.3,746.0,547,351.0,97.0,3.0,97.0,3.0,83.0,17.0,13.0,3.0,0.0,92.0,8.0,2980.0,2460.0,1590.0,2330.0,2590.0,3490.0,1950.0,3180.0,1180.0,1140.0,890.0,940.0,1010.0,1350.0,1020.0,1210.0,NaN,90,60,50,20,0,170.0,500.0,310.0,730,75.0,82.0,60.0,23.0,18.0,1100,38.9,33.2,38.4,20.3,40.0,28.7,26.2,1.7,4.2,6.2,7.5,259.7,20.0,40.0,10.0,260.0,35.0,11.3,60.0,49.0,150,10.0,30.0,25.0,5.0,15.0,25.0,25.0,15.0,790,585,205,1.4,463.0,105,3.8,0.6,1.2,0.9,1.0,171,170,1,9463,1.0,5.0,147.0
7,7,Verspreide huizen Eext,Aa en Hunze,Buurt,BU16800109,1,180,90,90,10,15,35,55,65,75,85,15,10,165,5,10,165,0,5,5,5,5,6.0,0,6.0,95,30,40,15,2.0,11.0,51,486.0,96.0,4.0,94.0,6.0,92.0,8.0,0.0,8.0,0.0,96.0,4.0,3640.0,NaN,NaN,NaN,NaN,3630.0,NaN,3530.0,1330.0,NaN,NaN,NaN,NaN,1350.0,NaN,1340.0,NaN,10,10,0,0,0,NaN,NaN,NaN,90,NaN,NaN,NaN,NaN,NaN,200,40.0,35.5,41.9,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,0.0,60.0,NaN,NaN,NaN,NaN,45,5.0,0.0,5.0,0.0,5.0,10.0,10.0,10.0,105,75,30,1.1,7.0,15,3.6,2.6,2.0,2.1,1.3,1618,1614,4,9463,1.0,5.0,37.0
9,9,Anloo,Aa en Hunze,Buurt,BU16800200,1,325,165,160,45,30,55,115,85,125,160,30,10,295,10,25,295,5,10,5,10,0,6.0,5,9.0,140,35,60,50,2.3,569.0,145,405.0,97.0,3.0,95.0,5.0,80.0,20.0,14.0,6.0,0.0,94.0,6.0,3130.0,NaN,NaN,NaN,2260.0,3520.0,2490.0,3290.0,1310.0,NaN,NaN,NaN,930.0,1440.0,1140.0,1350.0,NaN,20,20,10,10,0,110.0,50.0,80.0,160,67.0,73.0,58.0,16.0,27.0,300,41.0,34.2,43.3,22.6,39.6,24.3,20.0,3.6,6.5,8.0,8.7,352.7,10.0,20.0,0.0,80.0,10.0,13.5,15.0,43.0,60,5.0,5.0,15.0,0.0,5.0,10.0,15.0,5.0,190,135,50,1.3,328.0,25,2.2,2.7,2.5,0.5,2.0,57,57,0,9467,1.0,5.0,95.0

#### Waarom is het nodig om alleen op buurten te filteren en niet alle soorten erin te laten staan?
We filteren op alleen buurten omdat de dataset verschillende niveaus door elkaar heeft: Nederland, gemeenten, wijken en buurten. Als je die allemaal laat staan, tel je mensen dubbel, want een inwoner zit ook in zijn wijk, gemeente en Nederland. Daarnaast kun je een hele gemeente niet eerlijk vergelijken met één kleine buurt. Door alleen buurten te houden zit alles op hetzelfde niveau (dezelfde granulariteit) en is elke rij één buurt.

In [30]:
# Aantal rijen en kolommen dataframe
print(buurten.shape)

(14421, 128)

In [39]:
# code die gebruikt is
overzicht = pd.DataFrame({
    "kolomnaam": buurten.columns[0:32],
    "datatype": buurten.dtypes[0:32].astype(str),
    "waarden": buurten[buurten.columns[0:32]].count(),
    "missende waarden": buurten[buurten.columns[0:32]].isna().sum()
})

overzicht

mijn_num = [kolom for kolom in buurten.columns[0:32]
            if pd.api.types.is_numeric_dtype(buurten[kolom]) and kolom != "ID"]

buurten[mijn_num].agg(["max", "min", "mean", "median"]).T

                                 max  min         mean  median
AantalInwoners_5             29265.0  0.0  1235.024270   710.0
Mannen_6                     14025.0  0.0   613.673809   360.0
Vrouwen_7                    15240.0  0.0   621.348728   355.0
k_0Tot15Jaar_8                5095.0  0.0   189.147077    95.0
k_15Tot25Jaar_9               3905.0  0.0   151.883711    80.0
k_25Tot45Jaar_10              8670.0  0.0   312.513695   155.0
k_45Tot65Jaar_11              6870.0  0.0   331.758200   200.0
k_65JaarOfOuder_12            7870.0  0.0   249.710145   135.0
Ongehuwd_13                  15565.0  0.0   613.746273   325.0
Gehuwd_14                     9200.0  0.0   465.238194   280.0
Gescheiden_15                 3100.0  0.0    96.191318    45.0
Verweduwd_16                  2075.0  0.0    59.889051    25.0
Nederland_17                 16390.0  0.0   899.935857   550.0
EuropaExclusiefNederland_18   4365.0  0.0   112.114971    45.0
BuitenEuropa_19              12980.0  0.0   222.974135    45.0
Nederland_20                 16390.0  0.0   899.912281   550.0
EuropaExclusiefNederland_21   1060.0  0.0    41.953748    20.0
BuitenEuropa_22               6310.0  0.0   100.631371    20.0
EuropaExclusiefNederland_23   3790.0  0.0    70.174052    20.0
BuitenEuropa_24               6670.0  0.0   122.333056    25.0
GeboorteTotaal_25              320.0  0.0    11.375078     5.0
GeboorteRelatief_26            235.0  0.0     7.957738     8.0
SterfteTotaal_27               455.0  0.0    11.769641     5.0
SterfteRelatief_28             551.0  0.0     8.950656     6.0
HuishoudensTotaal_29         14180.0  0.0   573.389501   310.0
Eenpersoonshuishoudens_30     7485.0  0.0   226.421191    90.0

#### Omschrijving van de kolommen



| groep | kolomnaam | omschrijving | type | eenheden | waarden | missende waarden |
| --- | --- | --- | --- | --- | --- | --- |
| Identificatie | ID | Volgnummer van de rij in de dataset | int64 | nummer | 14421 | 0 |
| Identificatie | WijkenEnBuurten | Naam van de buurt | str | naam | 14421 | 0 |
| Identificatie | Gemeentenaam_1 | Naam van de gemeente waarin de buurt ligt | str | naam | 14421 | 0 |
| Identificatie | SoortRegio_2 | Soort regio; na filteren altijd ‘Buurt’ | str | omschrijving | 14421 | 0 |
| Identificatie | Codering_3 | Unieke CBS-code van de buurt | str | code | 14421 | 0 |
| Identificatie | IndelingswijzigingGemeenteWijkBuurt_4 | Geeft aan of de gemeente-, wijk- of buurtindeling is gewijzigd | str | code | 14421 | 0 |
| Bevolking | AantalInwoners_5 | Totaal aantal inwoners op 1 januari | int64 | aantal | 14421 | 0 |
| Bevolking | Mannen_6 | Aantal mannelijke inwoners | int64 | aantal | 14421 | 0 |
| Bevolking | Vrouwen_7 | Aantal vrouwelijke inwoners | int64 | aantal | 14421 | 0 |
| Bevolking | k_0Tot15Jaar_8 | Aantal inwoners van 0 tot 15 jaar | int64 | aantal | 14421 | 0 |
| Bevolking | k_15Tot25Jaar_9 | Aantal inwoners van 15 tot 25 jaar | int64 | aantal | 14421 | 0 |
| Bevolking | k_25Tot45Jaar_10 | Aantal inwoners van 25 tot 45 jaar | int64 | aantal | 14421 | 0 |
| Bevolking | k_45Tot65Jaar_11 | Aantal inwoners van 45 tot 65 jaar | int64 | aantal | 14421 | 0 |
| Bevolking | k_65JaarOfOuder_12 | Aantal inwoners van 65 jaar of ouder | int64 | aantal | 14421 | 0 |
| Bevolking | Ongehuwd_13 | Aantal ongehuwde inwoners | int64 | aantal | 14421 | 0 |
| Bevolking | Gehuwd_14 | Aantal gehuwde inwoners | int64 | aantal | 14421 | 0 |
| Bevolking | Gescheiden_15 | Aantal gescheiden inwoners | int64 | aantal | 14421 | 0 |
| Bevolking | Verweduwd_16 | Aantal verweduwde inwoners | int64 | aantal | 14421 | 0 |
| Bevolking | Nederland_17 | Aantal inwoners met Nederland als herkomstland | int64 | aantal | 14421 | 0 |
| Bevolking | EuropaExclusiefNederland_18 | Aantal inwoners met een herkomstland in Europa, buiten Nederland | int64 | aantal | 14421 | 0 |
| Bevolking | BuitenEuropa_19 | Aantal inwoners met een herkomstland buiten Europa | int64 | aantal | 14421 | 0 |
| Bevolking | Nederland_20 | Aantal inwoners geboren in Nederland met Nederland als herkomstland | int64 | aantal | 14421 | 0 |
| Bevolking | EuropaExclusiefNederland_21 | Aantal inwoners geboren in Nederland met een herkomstland in Europa, buiten Nederland | int64 | aantal | 14421 | 0 |
| Bevolking | BuitenEuropa_22 | Aantal inwoners geboren in Nederland met een herkomstland buiten Europa | int64 | aantal | 14421 | 0 |
| Bevolking | EuropaExclusiefNederland_23 | Aantal inwoners geboren buiten Nederland met een herkomstland in Europa | int64 | aantal | 14421 | 0 |
| Bevolking | BuitenEuropa_24 | Aantal inwoners geboren buiten Nederland met een herkomstland buiten Europa | int64 | aantal | 14421 | 0 |
| Bevolking | GeboorteTotaal_25 | Aantal levend geborenen in het verslagjaar | int64 | aantal | 14421 | 0 |
| Bevolking | GeboorteRelatief_26 | Aantal geboorten per 1.000 inwoners | float64 | per 1.000 inwoners | 14410 | 11 |
| Bevolking | SterfteTotaal_27 | Aantal overledenen in het verslagjaar | int64 | aantal | 14421 | 0 |
| Bevolking | SterfteRelatief_28 | Aantal sterfgevallen per 1.000 inwoners | float64 | per 1.000 inwoners | 14409 | 12 |
| Huishoudens | HuishoudensTotaal_29 | Totaal aantal particuliere huishoudens | int64 | aantal | 14421 | 0 |
| Huishoudens | Eenpersoonshuishoudens_30 | Aantal huishoudens bestaande uit één persoon | int64 | aantal | 14421 | 0 |


#### Extra omschrijving numerieke kolommen

| kolomnaam | maximum | minimum | gemiddelde | mediaan |
|---|---|---|---|---|
| AantalInwoners_5 | 29265 | 0 | 1235.02 | 710 |
| Mannen_6 | 14025 | 0 | 613.67 | 360 |
| Vrouwen_7 | 15240 | 0 | 621.35 | 355 |
| k_0Tot15Jaar_8 | 5095 | 0 | 189.15 | 95 |
| k_15Tot25Jaar_9 | 3905 | 0 | 151.88 | 80 |
| k_25Tot45Jaar_10 | 8670 | 0 | 312.51 | 155 |
| k_45Tot65Jaar_11 | 6870 | 0 | 331.76 | 200 |
| k_65JaarOfOuder_12 | 7870 | 0 | 249.71 | 135 |
| Ongehuwd_13 | 15565 | 0 | 613.75 | 325 |
| Gehuwd_14 | 9200 | 0 | 465.24 | 280 |
| Gescheiden_15 | 3100 | 0 | 96.19 | 45 |
| Verweduwd_16 | 2075 | 0 | 59.89 | 25 |
| Nederland_17 | 16390 | 0 | 899.94 | 550 |
| EuropaExclusiefNederland_18 | 4365 | 0 | 112.11 | 45 |
| BuitenEuropa_19 | 12980 | 0 | 222.97 | 45 |
| Nederland_20 | 16390 | 0 | 899.91 | 550 |
| EuropaExclusiefNederland_21 | 1060 | 0 | 41.95 | 20 |
| BuitenEuropa_22 | 6310 | 0 | 100.63 | 20 |
| EuropaExclusiefNederland_23 | 3790 | 0 | 70.17 | 20 |
| BuitenEuropa_24 | 6670 | 0 | 122.33 | 25 |
| GeboorteTotaal_25 | 320 | 0 | 11.38 | 5 |
| GeboorteRelatief_26 | 235 | 0 | 7.96 | 8 |
| SterfteTotaal_27 | 455 | 0 | 11.77 | 5 |
| SterfteRelatief_28 | 551 | 0 | 8.95 | 6 |
| HuishoudensTotaal_29 | 14180 | 0 | 573.39 | 310 |
| Eenpersoonshuishoudens_30 | 7485 | 0 | 226.42 | 90 |

#### Relevante kolommen
...

In [5]:
# Verwijderen van irrelevante kolommen

#### Onderbouwing te veel missende waardes
...

In [6]:
# Verwijderen van kolommen met te veel missende waardes

#### Basisstatistieken

In [7]:
# Basisstatistieken:
# Totalen per gemeente

In [8]:
# Basisstatistieken:
# Percentages

### Voorlopige conclusie

## Sprint 4

## Sprint 5

## Sprint 6

### Eindadvies